# Generated by Django 4.0.2 on 2022-02-14 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter album name', max_length=255)),
                ('release_date', models.DateTimeField()),
                ('album_art', models.ImageField(default='media/album_art/default.png', upload_to='media/album_art/')),
                ('detail', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('poster', models.ImageField(default='posters/default.jpeg', upload_to='posters/')),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('time', models.PositiveSmallIntegerField(default='6', help_text='Duration of the event')),
                ('location', models.CharField(default='Kisumu', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(help_text='Location where picture was taken', max_length=255)),
                ('picture', models.ImageField(help_text='upload picture', upload_to='media/gallery/')),
                ('featured', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter your full name', max_length=255)),
                ('age', models.PositiveIntegerField(help_text='Enter your age')),
                ('leaders_pic', models.ImageField(upload_to='media/leaders/')),
                ('phone', models.CharField(help_text='Enter a number beginning with 07', max_length=10)),
                ('term_start', models.DateField()),
                ('term_end', models.DateField()),
                ('current', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter your full name', max_length=255)),
                ('age', models.PositiveIntegerField(help_text='Enter your age')),
                ('phone', models.CharField(help_text='Enter a number beginning with 07', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='VideoTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Track's name", max_length=255)),
                ('video', models.FileField(help_text='upload video file if available', upload_to='media/video/')),
                ('link', models.TextField(help_text='Enter the youtube share link', null=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='family_chorale.album')),
            ],
        ),
        migrations.CreateModel(
            name='AudioTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Track's name", max_length=255)),
                ('audio', models.FileField(help_text='upload audio file if available', upload_to='media/audio/')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='family_chorale.album')),
            ],
        ),
    ]
