# Generated by Django 4.0.2 on 2022-02-14 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family_chorale', '0002_rename_event_events'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
    ]
