# Generated by Django 4.0.2 on 2022-02-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_chorale', '0003_rename_events_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='upcoming',
            field=models.BooleanField(default=False),
        ),
    ]
