# Generated by Django 4.0.2 on 2022-02-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_chorale', '0004_event_upcoming'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videotrack',
            name='link',
            field=models.TextField(blank=True, help_text='Enter the youtube share link', null=True),
        ),
    ]
